{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finopsiq
  namespace: {{ .Values.environment.namespace | quote }}
  labels:
    app.kubernetes.io/name: finopsiq
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect | quote }}
    {{- if .Values.ingress.sslCertificateName }}
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{ .Values.ingress.sslCertificateName | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - {{- if .Values.ingress.hostname }}
      host: {{ .Values.ingress.hostname | quote }}
      {{- end }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
{{- end }}
