{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $service.namespace }}
  labels:
    {{- include "finops.labels" $ | nindent 4 }}
    {{- include "finops.selectorLabels" (dict "name" $name) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "finops.selectorLabels" (dict "name" $name) | nindent 4 }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
