apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.environment.namespace | quote }}
  labels:
    app.kubernetes.io/name: finopsiq
    app.kubernetes.io/environment: {{ .Values.environment.name | quote }}
