---
# yamllint disable-rule: line-length
# .github/workflows/ci-cd.yml
name: CI‑CD – Azure Cost Advisor (Orchestrator)

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validation:
    uses: ./.github/workflows/validation.yml
    secrets: inherit # yamllint disable-rule: truthy

  bootstrap:
    needs: validation
    uses: ./.github/workflows/bootstrap.yml
    secrets: inherit # yamllint disable-rule: truthy

  platform:
    needs: bootstrap
    uses: ./.github/workflows/platform.yml
    secrets: inherit # yamllint disable-rule: truthy

  postinfra:
    needs: platform
    uses: ./.github/workflows/postinfra.yml
    secrets: inherit # yamllint disable-rule: truthy

  build:
    needs: postinfra
    uses: ./.github/workflows/build.yml
    secrets: inherit # yamllint disable-rule: truthy

  kvpopulate:
    needs: build
    uses: ./.github/workflows/kvpopulate.yml
    secrets: inherit # yamllint disable-rule: truthy

  helmdeploy:
    needs: kvpopulate
    uses: ./.github/workflows/helmdeploy.yml
    secrets: inherit # yamllint disable-rule: truthy

  agic:
    needs: helmdeploy
    uses: ./.github/workflows/agic.yml
    secrets: inherit # yamllint disable-rule: truthy

  smoke:
    needs: agic
    uses: ./.github/workflows/smoke.yml
    secrets: inherit # yamllint disable-rule: truthy
