apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: {{ .Values.environment.namespace | quote }}
  labels:
    app.kubernetes.io/name: finopsiq
    app.kubernetes.io/component: auth-service
  annotations:
    azure.workload.identity/client-id: {{ .Values.services.auth.serviceAccountClientId | quote }}
